// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCppg7lK6LRg2aKKXd2-6GXrg1b34PGbak',
    appId: '1:248269027604:web:488dd8e066d9b875b6ea01',
    messagingSenderId: '248269027604',
    projectId: 'flutter-chat-app-3ca14',
    authDomain: 'flutter-chat-app-3ca14.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3ca14.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSxh-MzR7vcQE35emVn5_5eX9oMp27h24',
    appId: '1:248269027604:android:82853e501a8d412fb6ea01',
    messagingSenderId: '248269027604',
    projectId: 'flutter-chat-app-3ca14',
    storageBucket: 'flutter-chat-app-3ca14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-TjD0u6E9B-NRaf3iujUmEqFqfPn0ASQ',
    appId: '1:248269027604:ios:ccbad389178034bbb6ea01',
    messagingSenderId: '248269027604',
    projectId: 'flutter-chat-app-3ca14',
    storageBucket: 'flutter-chat-app-3ca14.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-TjD0u6E9B-NRaf3iujUmEqFqfPn0ASQ',
    appId: '1:248269027604:ios:35d4ef96f0c75225b6ea01',
    messagingSenderId: '248269027604',
    projectId: 'flutter-chat-app-3ca14',
    storageBucket: 'flutter-chat-app-3ca14.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
